name: Run tests

on: [push]

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test

  doctest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: dtolnay/rust-toolchain@stable
      - name: Build and install emire
        run: |
          pip install maturin
          maturin build
          pip install target/wheels/*.whl
      - name: Test Usage code examples
        run: python -m doctest -v README.md
